In [24]:
from pandas import read_csv, read_excel, date_range, RangeIndex, DataFrame, to_datetime
from datetime import datetime, timedelta, date
from matplotlib import pyplot
import statistics
from pandas.tseries.offsets import MonthEnd
import calendar

In [2]:
# Load data using read_excel
# transacciones_nomina_df = read_excel('20210513 mmelero (249236).xlsx', sheet_name='Hoja1')

# 20210812 modificación
transacciones_nomina_df = read_excel('20210513 mmelero (249236)_dummy.xlsx', sheet_name='Hoja1')

transacciones_nomina_df

,Unnamed: 0,TRANSACTION_DATE,AMOUNT,id,ID de categoría,Nombre de categoría,level,ID,name,Proveedor,Trademark,Sector,CATEGORY_IS_FINANCIAL,CATEGORY_IS_TRANSFER
0,0,2020-07-24,-1.20,84.0,84.0,category.parking_84,2.0,5.0,category.vehiculos_5,NaN,NaN,NaN,False,False
1,1,2020-07-23,-4.50,117.0,117.0,category.regalos_celebraciones_117,2.0,8.0,category.gastos_personales_8,NaN,NaN,NaN,False,False
2,2,2020-07-23,-13.53,70.0,70.0,category.supermercados_70,2.0,4.0,category.alimentacion_4,SPAR,SPAR,Supermercados,False,False
3,3,2020-07-22,-51.40,222.0,222.0,category.adsl_222,3.0,521.0,Comunicaciones y TV,Jazz Telecom,Jazztel,Compañías telecomunicaciones,False,False
4,4,2020-07-22,-11.00,70.0,70.0,category.supermercados_70,2.0,4.0,category.alimentacion_4,Mercadona,Mercadona,Supermercados,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1482,1482,2016-09-05,1533.02,18.0,18.0,category.retribucion_liquida_18,3.0,576.0,Nómina,NaN,NaN,NaN,False,False
1483,1483,2016-09-05,-617.47,126.0,126.0,category.liquidacion_tarjeta_126,3.0,478.0,category.tarjetas_credito_478,NaN,NaN,NaN,True,True
1484,1484,2016-09-05,-138.08,125.0,125.0,category.cuotas_125,3.0,127.0,category.otros_pasivos_127,NaN,NaN,NaN,True,False
1485,1485,2016-09-01,-32.22,90.0,90.0,category.seguro_salud_90,2.0,6.0,category.salud_6,Sanitas S.A. de Seguros,Sanitas,Seguros de salud,True,False
1486,1486,2016-09-01,-33.00,434.0,434.0,category.cuotas_434,3.0,115.0,category.deportes_115,Royal Sport Center,Royal Sport Center,Clubs deportivos,False,False

In [3]:
# nos quedamos con transacciones desde 'Fecha transacción' hasta 'ID Categoría'
# transacciones_nomina_df=transacciones_nomina_df.iloc[:,0:3]

# 20210812 modificación
transacciones_nomina_df=transacciones_nomina_df.iloc[:,1:4]

transacciones_nomina_df

     TRANSACTION_DATE   AMOUNT     id
0          2020-07-24    -1.20   84.0
1          2020-07-23    -4.50  117.0
2          2020-07-23   -13.53   70.0
3          2020-07-22   -51.40  222.0
4          2020-07-22   -11.00   70.0
...               ...      ...    ...
1482       2016-09-05  1533.02   18.0
1483       2016-09-05  -617.47  126.0
1484       2016-09-05  -138.08  125.0
1485       2016-09-01   -32.22   90.0
1486       2016-09-01   -33.00  434.0

[1487 rows x 3 columns]

In [4]:
# 20210812 modificación
dict_temp = {'TRANSACTION_DATE': 'Fecha transacción', 'AMOUNT': 'Importe', 'id': 'ID Categoría'}
transacciones_nomina_df.rename(columns=dict_temp, inplace=True)
transacciones_nomina_df

     Fecha transacción  Importe  ID Categoría
0           2020-07-24    -1.20          84.0
1           2020-07-23    -4.50         117.0
2           2020-07-23   -13.53          70.0
3           2020-07-22   -51.40         222.0
4           2020-07-22   -11.00          70.0
...                ...      ...           ...
1482        2016-09-05  1533.02          18.0
1483        2016-09-05  -617.47         126.0
1484        2016-09-05  -138.08         125.0
1485        2016-09-01   -32.22          90.0
1486        2016-09-01   -33.00         434.0

[1487 rows x 3 columns]

In [5]:
SALARIO = 950.0
PENSION = 609.9
DESEMPLEO = 451.92

"""
nos quedamos con las transacciones que cumplan las siguientes condicion:
(18.0) retribucion_liquida_18 >= 950.0 eur OR
(588.0) Prestación de Seguridad Social >= 609.9 eur OR
(589.0) Prestación de desempleo >= 451.92 eur
"""

transacciones_nomina_df=\
transacciones_nomina_df[(transacciones_nomina_df['ID Categoría'] == 18.0) & (transacciones_nomina_df['Importe'] >= SALARIO) |
                       (transacciones_nomina_df['ID Categoría'] == 588.0) & (transacciones_nomina_df['Importe'] >= PENSION) |
                       (transacciones_nomina_df['ID Categoría'] == 589.0) & (transacciones_nomina_df['Importe'] >= DESEMPLEO)]
transacciones_nomina_df

     Fecha transacción  Importe  ID Categoría
16          2020-07-15  1888.97          18.0
33          2020-07-06  2031.55          18.0
127         2020-05-05  2004.95          18.0
134         2019-12-20  1758.22          18.0
148         2019-12-04  1600.00          18.0
164         2019-11-06  1675.77          18.0
181         2019-10-02  1675.77          18.0
227         2019-06-04  1675.77          18.0
275         2019-05-03  3456.76          18.0
306         2019-04-09  1500.00          18.0
310         2019-04-03  1675.77          18.0
333         2019-03-04  1675.77          18.0
370         2019-02-04  1675.77          18.0
431         2018-12-21  1882.53          18.0
437         2018-12-04  1789.39          18.0
487         2018-11-02  2382.94          18.0
517         2018-10-02  2515.38          18.0
542         2018-09-03  1789.39          18.0
605         2018-08-01  1789.39          18.0
628         2018-07-26  1882.53          18.0
642         2018-07-03  1789.39          18.0
697         2018-06-01  1799.26          18.0
744         2018-05-04  1799.26          18.0
798         2018-04-04  1799.26          18.0
856         2018-03-05  3964.43          18.0
906         2018-02-01  2451.77          18.0
936         2017-12-01  1630.93          18.0
953         2017-11-06  1678.79          18.0
982         2017-10-03  2099.33          18.0
1004        2017-09-01  1812.12          18.0
1068        2017-08-03  1623.42          18.0
1069        2017-08-03  2172.61          18.0
1115        2017-07-03  1632.61          18.0
1154        2017-06-02  1947.61          18.0
1193        2017-05-02  2178.64          18.0
1209        2017-04-03  1642.52          18.0
1247        2017-03-02  1293.45          18.0
1284        2017-02-02  1640.70          18.0
1340        2016-12-28  1640.70          18.0
1346        2016-12-21  1633.41          18.0
1374        2016-12-07  1640.70          18.0
1428        2016-11-02  1640.70          18.0
1467        2016-10-04  1633.95          18.0
1482        2016-09-05  1533.02          18.0

In [6]:
# borramos la columna de 'ID Categoría'
transacciones_nomina_df=transacciones_nomina_df.drop(['ID Categoría'], axis=1)
transacciones_nomina_df

     Fecha transacción  Importe
16          2020-07-15  1888.97
33          2020-07-06  2031.55
127         2020-05-05  2004.95
134         2019-12-20  1758.22
148         2019-12-04  1600.00
164         2019-11-06  1675.77
181         2019-10-02  1675.77
227         2019-06-04  1675.77
275         2019-05-03  3456.76
306         2019-04-09  1500.00
310         2019-04-03  1675.77
333         2019-03-04  1675.77
370         2019-02-04  1675.77
431         2018-12-21  1882.53
437         2018-12-04  1789.39
487         2018-11-02  2382.94
517         2018-10-02  2515.38
542         2018-09-03  1789.39
605         2018-08-01  1789.39
628         2018-07-26  1882.53
642         2018-07-03  1789.39
697         2018-06-01  1799.26
744         2018-05-04  1799.26
798         2018-04-04  1799.26
856         2018-03-05  3964.43
906         2018-02-01  2451.77
936         2017-12-01  1630.93
953         2017-11-06  1678.79
982         2017-10-03  2099.33
1004        2017-09-01  1812.12
1068        2017-08-03  1623.42
1069        2017-08-03  2172.61
1115        2017-07-03  1632.61
1154        2017-06-02  1947.61
1193        2017-05-02  2178.64
1209        2017-04-03  1642.52
1247        2017-03-02  1293.45
1284        2017-02-02  1640.70
1340        2016-12-28  1640.70
1346        2016-12-21  1633.41
1374        2016-12-07  1640.70
1428        2016-11-02  1640.70
1467        2016-10-04  1633.95
1482        2016-09-05  1533.02

In [7]:
# ordenamos las filas del dataframe por fechas en orden ascendente
transacciones_nomina_df.sort_values(by='Fecha transacción', inplace=True)
transacciones_nomina_df

     Fecha transacción  Importe
1482        2016-09-05  1533.02
1467        2016-10-04  1633.95
1428        2016-11-02  1640.70
1374        2016-12-07  1640.70
1346        2016-12-21  1633.41
1340        2016-12-28  1640.70
1284        2017-02-02  1640.70
1247        2017-03-02  1293.45
1209        2017-04-03  1642.52
1193        2017-05-02  2178.64
1154        2017-06-02  1947.61
1115        2017-07-03  1632.61
1068        2017-08-03  1623.42
1069        2017-08-03  2172.61
1004        2017-09-01  1812.12
982         2017-10-03  2099.33
953         2017-11-06  1678.79
936         2017-12-01  1630.93
906         2018-02-01  2451.77
856         2018-03-05  3964.43
798         2018-04-04  1799.26
744         2018-05-04  1799.26
697         2018-06-01  1799.26
642         2018-07-03  1789.39
628         2018-07-26  1882.53
605         2018-08-01  1789.39
542         2018-09-03  1789.39
517         2018-10-02  2515.38
487         2018-11-02  2382.94
437         2018-12-04  1789.39
431         2018-12-21  1882.53
370         2019-02-04  1675.77
333         2019-03-04  1675.77
310         2019-04-03  1675.77
306         2019-04-09  1500.00
275         2019-05-03  3456.76
227         2019-06-04  1675.77
181         2019-10-02  1675.77
164         2019-11-06  1675.77
148         2019-12-04  1600.00
134         2019-12-20  1758.22
127         2020-05-05  2004.95
33          2020-07-06  2031.55
16          2020-07-15  1888.97

In [8]:
# renombramos columnas
transacciones_nomina_df.columns = ['FECHA', 'IMPORTE']
transacciones_nomina_df

          FECHA  IMPORTE
1482 2016-09-05  1533.02
1467 2016-10-04  1633.95
1428 2016-11-02  1640.70
1374 2016-12-07  1640.70
1346 2016-12-21  1633.41
1340 2016-12-28  1640.70
1284 2017-02-02  1640.70
1247 2017-03-02  1293.45
1209 2017-04-03  1642.52
1193 2017-05-02  2178.64
1154 2017-06-02  1947.61
1115 2017-07-03  1632.61
1068 2017-08-03  1623.42
1069 2017-08-03  2172.61
1004 2017-09-01  1812.12
982  2017-10-03  2099.33
953  2017-11-06  1678.79
936  2017-12-01  1630.93
906  2018-02-01  2451.77
856  2018-03-05  3964.43
798  2018-04-04  1799.26
744  2018-05-04  1799.26
697  2018-06-01  1799.26
642  2018-07-03  1789.39
628  2018-07-26  1882.53
605  2018-08-01  1789.39
542  2018-09-03  1789.39
517  2018-10-02  2515.38
487  2018-11-02  2382.94
437  2018-12-04  1789.39
431  2018-12-21  1882.53
370  2019-02-04  1675.77
333  2019-03-04  1675.77
310  2019-04-03  1675.77
306  2019-04-09  1500.00
275  2019-05-03  3456.76
227  2019-06-04  1675.77
181  2019-10-02  1675.77
164  2019-11-06  1675.77
148  2019-12-04  1600.00
134  2019-12-20  1758.22
127  2020-05-05  2004.95
33   2020-07-06  2031.55
16   2020-07-15  1888.97

In [9]:
# agrupamos los valores por FECHA para quitarnos los duplicados
transacciones_nomina_df=transacciones_nomina_df.groupby(transacciones_nomina_df.FECHA).sum()
transacciones_nomina_df

            IMPORTE
FECHA
2016-09-05  1533.02
2016-10-04  1633.95
2016-11-02  1640.70
2016-12-07  1640.70
2016-12-21  1633.41
2016-12-28  1640.70
2017-02-02  1640.70
2017-03-02  1293.45
2017-04-03  1642.52
2017-05-02  2178.64
2017-06-02  1947.61
2017-07-03  1632.61
2017-08-03  3796.03
2017-09-01  1812.12
2017-10-03  2099.33
2017-11-06  1678.79
2017-12-01  1630.93
2018-02-01  2451.77
2018-03-05  3964.43
2018-04-04  1799.26
2018-05-04  1799.26
2018-06-01  1799.26
2018-07-03  1789.39
2018-07-26  1882.53
2018-08-01  1789.39
2018-09-03  1789.39
2018-10-02  2515.38
2018-11-02  2382.94
2018-12-04  1789.39
2018-12-21  1882.53
2019-02-04  1675.77
2019-03-04  1675.77
2019-04-03  1675.77
2019-04-09  1500.00
2019-05-03  3456.76
2019-06-04  1675.77
2019-10-02  1675.77
2019-11-06  1675.77
2019-12-04  1600.00
2019-12-20  1758.22
2020-05-05  2004.95
2020-07-06  2031.55
2020-07-15  1888.97

In [10]:
# hacemos un dataframe con el dia que pagaron la nomina para ver en que dias se cobra mas frecuentemente la misma

In [11]:
# hacemos una columna con la fecha a partir del índice
transacciones_nomina_df['FECHA']=transacciones_nomina_df.index
transacciones_nomina_df

            IMPORTE      FECHA
FECHA
2016-09-05  1533.02 2016-09-05
2016-10-04  1633.95 2016-10-04
2016-11-02  1640.70 2016-11-02
2016-12-07  1640.70 2016-12-07
2016-12-21  1633.41 2016-12-21
2016-12-28  1640.70 2016-12-28
2017-02-02  1640.70 2017-02-02
2017-03-02  1293.45 2017-03-02
2017-04-03  1642.52 2017-04-03
2017-05-02  2178.64 2017-05-02
2017-06-02  1947.61 2017-06-02
2017-07-03  1632.61 2017-07-03
2017-08-03  3796.03 2017-08-03
2017-09-01  1812.12 2017-09-01
2017-10-03  2099.33 2017-10-03
2017-11-06  1678.79 2017-11-06
2017-12-01  1630.93 2017-12-01
2018-02-01  2451.77 2018-02-01
2018-03-05  3964.43 2018-03-05
2018-04-04  1799.26 2018-04-04
2018-05-04  1799.26 2018-05-04
2018-06-01  1799.26 2018-06-01
2018-07-03  1789.39 2018-07-03
2018-07-26  1882.53 2018-07-26
2018-08-01  1789.39 2018-08-01
2018-09-03  1789.39 2018-09-03
2018-10-02  2515.38 2018-10-02
2018-11-02  2382.94 2018-11-02
2018-12-04  1789.39 2018-12-04
2018-12-21  1882.53 2018-12-21
2019-02-04  1675.77 2019-02-04
2019-03-04  1675.77 2019-03-04
2019-04-03  1675.77 2019-04-03
2019-04-09  1500.00 2019-04-09
2019-05-03  3456.76 2019-05-03
2019-06-04  1675.77 2019-06-04
2019-10-02  1675.77 2019-10-02
2019-11-06  1675.77 2019-11-06
2019-12-04  1600.00 2019-12-04
2019-12-20  1758.22 2019-12-20
2020-05-05  2004.95 2020-05-05
2020-07-06  2031.55 2020-07-06
2020-07-15  1888.97 2020-07-15

In [12]:
# hacemos una columna con el dia a partir de la columna de la fecha
transacciones_nomina_df['DIA'] = transacciones_nomina_df['FECHA'].dt.day
transacciones_nomina_df

            IMPORTE      FECHA  DIA
FECHA
2016-09-05  1533.02 2016-09-05    5
2016-10-04  1633.95 2016-10-04    4
2016-11-02  1640.70 2016-11-02    2
2016-12-07  1640.70 2016-12-07    7
2016-12-21  1633.41 2016-12-21   21
2016-12-28  1640.70 2016-12-28   28
2017-02-02  1640.70 2017-02-02    2
2017-03-02  1293.45 2017-03-02    2
2017-04-03  1642.52 2017-04-03    3
2017-05-02  2178.64 2017-05-02    2
2017-06-02  1947.61 2017-06-02    2
2017-07-03  1632.61 2017-07-03    3
2017-08-03  3796.03 2017-08-03    3
2017-09-01  1812.12 2017-09-01    1
2017-10-03  2099.33 2017-10-03    3
2017-11-06  1678.79 2017-11-06    6
2017-12-01  1630.93 2017-12-01    1
2018-02-01  2451.77 2018-02-01    1
2018-03-05  3964.43 2018-03-05    5
2018-04-04  1799.26 2018-04-04    4
2018-05-04  1799.26 2018-05-04    4
2018-06-01  1799.26 2018-06-01    1
2018-07-03  1789.39 2018-07-03    3
2018-07-26  1882.53 2018-07-26   26
2018-08-01  1789.39 2018-08-01    1
2018-09-03  1789.39 2018-09-03    3
2018-10-02  2515.38 2018-10-02    2
2018-11-02  2382.94 2018-11-02    2
2018-12-04  1789.39 2018-12-04    4
2018-12-21  1882.53 2018-12-21   21
2019-02-04  1675.77 2019-02-04    4
2019-03-04  1675.77 2019-03-04    4
2019-04-03  1675.77 2019-04-03    3
2019-04-09  1500.00 2019-04-09    9
2019-05-03  3456.76 2019-05-03    3
2019-06-04  1675.77 2019-06-04    4
2019-10-02  1675.77 2019-10-02    2
2019-11-06  1675.77 2019-11-06    6
2019-12-04  1600.00 2019-12-04    4
2019-12-20  1758.22 2019-12-20   20
2020-05-05  2004.95 2020-05-05    5
2020-07-06  2031.55 2020-07-06    6
2020-07-15  1888.97 2020-07-15   15

In [13]:
transacciones_nomina_df['FECHA']

FECHA
2016-09-05   2016-09-05
2016-10-04   2016-10-04
2016-11-02   2016-11-02
2016-12-07   2016-12-07
2016-12-21   2016-12-21
2016-12-28   2016-12-28
2017-02-02   2017-02-02
2017-03-02   2017-03-02
2017-04-03   2017-04-03
2017-05-02   2017-05-02
2017-06-02   2017-06-02
2017-07-03   2017-07-03
2017-08-03   2017-08-03
2017-09-01   2017-09-01
2017-10-03   2017-10-03
2017-11-06   2017-11-06
2017-12-01   2017-12-01
2018-02-01   2018-02-01
2018-03-05   2018-03-05
2018-04-04   2018-04-04
2018-05-04   2018-05-04
2018-06-01   2018-06-01
2018-07-03   2018-07-03
2018-07-26   2018-07-26
2018-08-01   2018-08-01
2018-09-03   2018-09-03
2018-10-02   2018-10-02
2018-11-02   2018-11-02
2018-12-04   2018-12-04
2018-12-21   2018-12-21
2019-02-04   2019-02-04
2019-03-04   2019-03-04
2019-04-03   2019-04-03
2019-04-09   2019-04-09
2019-05-03   2019-05-03
2019-06-04   2019-06-04
2019-10-02   2019-10-02
2019-11-06   2019-11-06
2019-12-04   2019-12-04
2019-12-20   2019-12-20
2020-05-05   2020-05-05
2020-07-06   2020-07-06
2020-07-15   2020-07-15
Name: FECHA, dtype: datetime64[ns]

In [14]:
# ESTO NO SE EJECUTA EN PRODUCCION
# comprobamos tipos datos columnas
transacciones_nomina_df.dtypes

IMPORTE           float64
FECHA      datetime64[ns]
DIA                 int64
dtype: object

In [15]:
# ESTO NO SE EJECUTA EN PRODUCCION
# miramos estadisticos de distribución
transacciones_nomina_df.describe()

           IMPORTE        DIA
count    43.000000  43.000000
mean   1930.353488   5.976744
std     559.275366   6.867759
min    1293.450000   1.000000
25%    1640.700000   2.000000
50%    1789.390000   4.000000
75%    1918.290000   5.500000
max    3964.430000  28.000000

In [16]:
# calculamos la moda
stat_mode = statistics.mode(transacciones_nomina_df['DIA'])
stat_mode

4

In [17]:
# extraemos el 1er cuartil
quartil1_dist = int(transacciones_nomina_df.describe().loc['25%']['DIA'])
quartil1_dist

2

In [18]:
# extraemos el 3er cuartil
quartil3_dist = int(transacciones_nomina_df.describe().loc['75%']['DIA'])
quartil3_dist

5

In [19]:
# ESTO NO SE EJECUTA EN PRODUCCION
start_date_str = '2018-12-20'
end_date_str = '2020-01-10'
mask = (transacciones_nomina_df['FECHA'] >= start_date_str) & (transacciones_nomina_df['FECHA'] <= end_date_str)
transacciones_nomina_df.loc[mask]

            IMPORTE      FECHA  DIA
FECHA
2018-12-21  1882.53 2018-12-21   21
2019-02-04  1675.77 2019-02-04    4
2019-03-04  1675.77 2019-03-04    4
2019-04-03  1675.77 2019-04-03    3
2019-04-09  1500.00 2019-04-09    9
2019-05-03  3456.76 2019-05-03    3
2019-06-04  1675.77 2019-06-04    4
2019-10-02  1675.77 2019-10-02    2
2019-11-06  1675.77 2019-11-06    6
2019-12-04  1600.00 2019-12-04    4
2019-12-20  1758.22 2019-12-20   20

In [20]:
iqr_dist = quartil3_dist - quartil1_dist
iqr_dist

3

In [21]:
# si NO cobramos a FIN DE MES
if stat_mode < 28:    
    iqr = iqr_dist
# si SÍ cobramos a FIN DE MES
else:
    # si quartil3_dist - quartil1_dist es mayor a 4 dias
    if iqr_dist > 4:
        iqr = 4
    else:
        iqr = iqr_dist
iqr

3

In [33]:
# 20210812 modificación
# esta es la linea que finalmente se ejecutara en producción pero no en pruebas e integración
real_current_date_obj = date.today()
real_current_date_obj

datetime.date(2021, 8, 13)

In [34]:
# 20210812 modificación
# esta es la linea que finalmente se ejecutara en producción pero no en pruebas e integración
real_current_date_str = str(real_current_date_obj)
real_current_date_str

'2021-08-13'

In [114]:
# pedimos al usuario la fecha (en produccion tomamos la fecha del sistema)
year = input('year: ')
month = input('month: ')
day = input('day: ')

year: 2020
month: 8
day: 31

In [115]:
# pasamos la fecha a string
current_date_str= year + '-' + month + '-' + day
current_date_str

'2020-8-31'

In [116]:
current_date_obj = datetime.strptime(current_date_str, '%Y-%m-%d')
current_date_obj

datetime.datetime(2020, 8, 31, 0, 0)

In [117]:
# pasamos iqr a formato datetime
iqr_obj = timedelta(days=iqr)
iqr_obj

datetime.timedelta(days=3)

In [118]:
# calculamos quartil3_obj en funcion de current_date_obj, quartil3_dist y si cobramos a FIN de MES o NO

# si SÍ cobramos a FIN de MES
if stat_mode >= 28:
    # quartil3_obj sera el ultimo dia del mes de current_date_obj
    quartil3 = calendar.monthrange(current_date_obj.year, current_date_obj.month)[1]
    quartil3_str = str(current_date_obj.year) + '-' + str(current_date_obj.month) + '-' + str(quartil3)
# si NO cobramos a FIN de MES    
else:
    quartil3_str = str(current_date_obj.year) + '-' + str(current_date_obj.month) + '-' + str(quartil3_dist)

quartil3_str

'2020-8-5'

In [119]:
q3_obj = datetime.strptime(quartil3_str, '%Y-%m-%d')
q3_obj

datetime.datetime(2020, 8, 5, 0, 0)

In [120]:
q1_obj = q3_obj - iqr_obj
q1_obj

datetime.datetime(2020, 8, 2, 0, 0)

In [121]:
lim_inf_obj = q1_obj - 1.5*iqr_obj
# quitamos partes de dias no enteros que haya podido introducir 1.5*iqr_obj
lim_inf_obj=lim_inf_obj.replace(hour=0, minute=0, second=0, microsecond=0)
lim_inf_obj

datetime.datetime(2020, 7, 28, 0, 0)

In [122]:
# calculamos limite superior de barrido segun cobremos a fin de mes o no
limSup_obj = q3_obj + timedelta(days=1)
limSup_obj

datetime.datetime(2020, 8, 6, 0, 0)

In [123]:
cobrado = False

In [124]:
for d in  range(int((limSup_obj - lim_inf_obj).days)):    
    # ESTA LINEA NO SE EJECUTA EN PRODUCCION
    fecha_str = str((lim_inf_obj + timedelta(d)).year) + '-' + str((lim_inf_obj + timedelta(d)).month) + '-' + \
    str((lim_inf_obj + timedelta(days=d)).day)
    # ESTA LINEA NO SE EJECUTA EN PRODUCCION
    print(fecha_str)
    if (lim_inf_obj + timedelta(days=d)) in transacciones_nomina_df.index:
        cobrado = True
        print ('El usuario cobró una nómina de ' + \
               str(transacciones_nomina_df['IMPORTE'][str(lim_inf_obj + timedelta(days=d))[:10]]) + \
               ' eur el día ' + str(lim_inf_obj + timedelta(d))[:10])
if not(cobrado):
    fecha_obj = limSup_obj - timedelta(days=1)
    fecha = str(fecha_obj.year) + '-' + str(fecha_obj.month) + '-' + str(fecha_obj.day)
    print(fecha + ': El usuario aún no ha cobrado la nómina. Hay que avisarle')

2020-7-28
2020-7-29
2020-7-30
2020-7-31
2020-8-1
2020-8-2
2020-8-3
2020-8-4
2020-8-5
2020-8-5: El usuario aún no ha cobrado la nómina. Hay que avisarle

In [125]:
# if para decidir si genero aviso

if not(cobrado) and current_date_obj == q3_obj:
    aviso = True
else:
    aviso = False

print('Aviso: ' + str(aviso))

Aviso: False

In [81]:
!python -V

Python 3.8.10

In [82]:
!pip list

Package                            Version

WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)

---------------------------------- -------------------
absl-py                            0.12.0
aiohttp                            3.7.4
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 2.0.3
anaconda-project                   0.10.0
anyio                              2.2.0
AnyQt                              0.0.13
argh                               0.26.2
argon2-cffi                        20.1.0
arviz                              0.11.2
asn1crypto                         1.4.0
astor                              0.8.1
astroid                            2.5
astropy                            4.2.1
astunparse                         1.6.3
async-generator                    1.10
async-timeout                      3.0.1
atomicwrites                       1.4.0
attrs                              21.2.0
autopep8                           1.5.6
Babel                              2.9.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
baycomp                            1.0.2
bcrypt                             3.2.0
beautifulsoup4                     4.9.3
bitarray                           2.1.0
bkcharts                           0.2
bleach                             3.3.0
blinker                            1.4
bokeh                              2.3.2
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
CacheControl                       0.12.6
cachetools                         4.2.2
certifi                            2020.12.5
cffi                               1.14.5
cftime                             1.5.0
chardet                            3.0.4
click                              8.0.1
cloudpickle                        1.6.0
clyent                             1.2.2
cmdstanpy                          0.9.75
colorama                           0.4.4
commonmark                         0.9.1
comtypes                           1.1.10
conda                              4.10.1
conda-build                        3.21.4
conda-content-trust                0+unknown
conda-pack                         0.6.0
conda-package-handling             1.7.3
conda-repo-cli                     1.0.4
conda-token                        0.3.0
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
convertdate                        2.3.2
coverage                           5.5
cryptography                       3.4.7
cycler                             0.10.0
Cython                             0.29.23
cytoolz                            0.11.0
dask                               2021.4.0
decorator                          4.4.2
defusedxml                         0.7.1
dictdiffer                         0.8.1
diff-match-patch                   20200713
dill                               0.3.3
distributed                        2021.5.0
docutils                           0.17.1
echo                               0.5
entrypoints                        0.3
ephem                              3.7.7.1
et-xmlfile                         1.1.0
fast-histogram                     0.0.0
fastcache                          1.1.0
fbprophet                          0.7.1
filelock                           3.0.12
flake8                             3.9.0
Flask                              1.1.2
flatbuffers                        1.12
freetype-py                        2.2.0
fsspec                             0.9.0
future                             0.18.2
gast                               0.4.0
gevent                             21.1.2
glob2                              0.7
glue-core                          1.0.1
glue-vispy-viewers                 1.0.2
glueviz                            1.0.0
gmpy2                              2.0.8
google-auth                        1.30.0
google-auth-oauthlib               0.4.4
google-pasta                       0.2.0
greenlet                           1.1.0
grpcio                             1.34.1
h11                                0.12.0
h2                                 4.0.0
h5py                               3.1.0
HeapDict                           1.0.1
hijri-converter                    2.1.1
holidays                           0.11.1
hpack                              4.0.0
html5lib                           1.1
httpcore                           0.13.3
httpx                              0.18.1
hyperframe                         6.0.1
idna                               2.10
imagecodecs                        2021.4.28
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 3.10.0
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.22.0
ipython-genutils                   0.2.0
ipywidgets                         7.6.3
isort                              5.8.0
itsdangerous                       2.0.1
jdcal                              1.4.1
jedi                               0.17.1
Jinja2                             3.0.0
joblib                             1.0.1
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.12
jupyter-console                    6.4.0
jupyter-core                       4.7.1
jupyter-packaging                  0.7.12
jupyter-server                     1.4.1
jupyterlab                         3.0.14
jupyterlab-pygments                0.1.2
jupyterlab-server                  2.4.0
jupyterlab-widgets                 1.0.0
Keras                              2.4.3
Keras-Applications                 1.0.8
keras-nightly                      2.5.0.dev2021032900
Keras-Preprocessing                1.1.2
keyring                            23.0.1
keyrings.alt                       4.0.2
kiwisolver                         1.3.1
korean-lunar-calendar              0.2.1
lazy-object-proxy                  1.6.0
libarchive-c                       2.9
llvmlite                           0.36.0
locket                             0.2.1
lockfile                           0.12.2
LunarCalendar                      0.0.9
lxml                               4.6.3
Mako                               1.1.4
Markdown                           3.3.4
MarkupSafe                         2.0.1
matplotlib                         3.3.4
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.3.0
mkl-random                         1.2.1
mkl-service                        2.3.0
mock                               4.0.3
more-itertools                     8.7.0
mpl-scatter-density                0.7
mpmath                             1.2.1
msgpack                            1.0.2
multidict                          5.1.0
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbclassic                          0.2.6
nbclient                           0.5.3
nbconvert                          6.0.7
nbformat                           5.1.3
nest-asyncio                       1.5.1
netCDF4                            1.5.6
networkx                           2.5.1
nltk                               3.6.2
nose                               1.3.7
notebook                           6.4.0
numba                              0.53.1
numexpr                            2.7.3
numpy                              1.19.5
numpydoc                           1.1.0
oauthlib                           3.1.0
olefile                            0.46
openpyxl                           3.0.7
openTSNE                           0.6.0
opt-einsum                         3.3.0
orange-canvas-core                 0.1.20
orange-widget-base                 4.13.1
Orange3                            3.26.0
packaging                          20.9
pandas                             1.2.4
pandocfilters                      1.4.3
paramiko                           2.7.2
parso                              0.7.0
partd                              1.2.0
path                               15.1.2
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.2.0
pip                                21.1.1
pkginfo                            1.7.0
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.10.1
prompt-toolkit                     3.0.17
protobuf                           3.14.0
psutil                             5.8.0
ptyprocess                         0.7.0
py                                 1.10.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.6
pydocstyle                         6.1.1
pyerfa                             2.0.0
pyflakes                           2.2.0
Pygments                           2.9.0
pygpu                              0.7.6
PyJWT                              2.0.1
pylint                             2.7.4
PyMeeus                            0.5.10
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
PyOpenGL                           3.1.1a1
pyOpenSSL                          20.0.1
pyparsing                          2.4.7
pyqtgraph                          0.11.0
pyreadline                         2.1
pyrsistent                         0.17.3
PySocks                            1.7.1
pystan                             2.19.1.1
pytest                             6.2.3
python-dateutil                    2.8.1
python-jsonrpc-server              0.4.0
python-language-server             0.35.1
python-louvain                     0.15
pytz                               2021.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.4.1
pyzmq                              20.0.0
qasync                             0.16.0
QDarkStyle                         3.0.2
QtAwesome                          1.0.2
qtconsole                          5.0.3
QtPy                               1.9.0
regex                              2021.4.4

requests                           2.25.1
requests-oauthlib                  1.3.0
rfc3986                            1.5.0
rope                               0.18.0
rsa                                4.7.2
Rtree                              0.9.7
ruamel-yaml-conda                  0.15.100
scikit-image                       0.18.1
scikit-learn                       0.24.2
scipy                              1.4.1
seaborn                            0.11.1
Send2Trash                         1.5.0
serverfiles                        0.3.0
setuptools                         52.0.0.post20210125
setuptools-git                     1.2
simplegeneric                      0.8.1
singledispatch                     0.0.0
sip                                4.19.13
six                                1.15.0
sniffio                            1.2.0
snowballstemmer                    2.1.0
sortedcollections                  2.1.0
sortedcontainers                   2.3.0
soupsieve                          2.2.1
Sphinx                             4.0.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.4.15
statsmodels                        0.12.2
sympy                              1.8
tables                             3.6.1
tblib                              1.7.0
tensorboard                        2.5.0
tensorboard-data-server            0.6.1
tensorboard-plugin-wit             1.6.0
tensorflow                         2.3.0
tensorflow-estimator               2.5.0
tensorflow-gpu                     2.5.0
termcolor                          1.1.0
terminado                          0.9.4
testpath                           0.4.4
Theano                             1.0.4
threadpoolctl                      2.1.0
tifffile                           2021.4.8
toml                               0.10.2
toolz                              0.11.1
tornado                            6.1
tqdm                               4.59.0
traitlets                          5.0.5
typing-extensions                  3.7.4.3
ujson                              4.0.2
unicodecsv                         0.14.1
urllib3                            1.26.4
vispy                              0.6.6
watchdog                           2.1.1
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.36.2
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.12.1
xarray                             0.18.0
xlrd                               2.0.1
XlsxWriter                         1.3.8
xlwings                            0.23.0
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.31.0
yarl                               1.6.3
zict                               2.0.0
zipp                               3.4.1
zope.event                         4.5.0
zope.interface                     5.3.0

In [83]:
!pip3 freeze

absl-py @ file:///C:/ci/absl-py_1615411229697/work
aiohttp @ file:///C:/ci/aiohttp_1614361024229/work
alabaster @ file:///home/ktietz/src/ci/alabaster_1611921544520/work
anaconda-client==1.7.2
anaconda-navigator==2.0.3
anaconda-project @ file:///tmp/build/80754af9/anaconda-project_1621348054992/work
anyio @ file:///C:/ci/anyio_1620153418380/work/dist
AnyQt @ file:///home/conda/feedstock_root/build_artifacts/anyqt_1620306236038/work
argh==0.26.2
argon2-cffi @ file:///C:/ci/argon2-cffi_1613037959010/work
arviz @ file:///tmp/build/80754af9/arviz_1614019183254/work
asn1crypto @ file:///tmp/build/80754af9/asn1crypto_1596577642040/work
astor==0.8.1
astroid @ file:///C:/ci/astroid_1613501047216/work
astropy @ file:///C:/ci/astropy_1617745647203/work
astunparse==1.6.3
async-generator @ file:///home/ktietz/src/ci/async_generator_1611927993394/work
async-timeout==3.0.1
atomicwrites==1.4.0
attrs @ file:///tmp/build/80754af9/attrs_1620827162558/work
autopep8 @ file:///tmp/build/80754af9/autopep8_1615918855173/work
Babel @ file:///tmp/build/80754af9/babel_1620871417480/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
backports.functools-lru-cache @ file:///tmp/build/80754af9/backports.functools_lru_cache_1618170165463/work
backports.shutil-get-terminal-size @ file:///tmp/build/80754af9/backports.shutil_get_terminal_size_1608222128777/work
backports.tempfile @ file:///home/linux1/recipes/ci/backports.tempfile_1610991236607/work
backports.weakref==1.0.post1
baycomp==1.0.2
bcrypt @ file:///C:/ci/bcrypt_1597936263757/work
beautifulsoup4 @ file:///home/linux1/recipes/ci/beautifulsoup4_1610988766420/work
bitarray @ file:///C:/ci/bitarray_1620827742606/work
bkcharts==0.2
bleach @ file:///tmp/build/80754af9/bleach_1612211392645/work
blinker==1.4
bokeh @ file:///C:/ci/bokeh_1620784067744/work
boto==2.49.0
Bottleneck==1.3.2
brotlipy==0.7.0
CacheControl==0.12.6
cachetools @ file:///tmp/build/80754af9/cachetools_1619597386817/work
certifi==2020.12.5
cffi @ file:///C:/ci/cffi_1613247279197/work
cftime @ file:///C:/ci/cftime_1621828404706/work
chardet @ file:///C:/ci/chardet_1605303225733/work
click @ file:///tmp/build/80754af9/click_1621604852318/work
cloudpickle @ file:///tmp/build/80754af9/cloudpickle_1598884132938/work
clyent==1.2.2
cmdstanpy==0.9.75
colorama @ file:///tmp/build/80754af9/colorama_1607707115595/work
commonmark==0.9.1
comtypes==1.1.10
conda==4.10.1
conda-build==3.21.4
conda-content-trust @ file:///tmp/build/80754af9/conda-content-trust_1617045594566/work
conda-pack @ file:///tmp/build/80754af9/conda-pack_1611163042455/work
conda-package-handling @ file:///C:/ci/conda-package-handling_1618262320430/work
conda-repo-cli @ file:///tmp/build/80754af9/conda-repo-cli_1620168426516/work
conda-token @ file:///tmp/build/80754af9/conda-token_1620076980546/work
conda-verify==3.4.2
contextlib2==0.6.0.post1
convertdate @ file:///home/conda/feedstock_root/build_artifacts/convertdate_1615678826465/work
coverage @ file:///C:/ci/coverage_1614615074147/work
cryptography @ file:///C:/ci/cryptography_1616769344312/work
cycler==0.10.0
Cython @ file:///C:/ci/cython_1618435363327/work
cytoolz==0.11.0
dask @ file:///tmp/build/80754af9/dask-core_1617390489108/work
decorator @ file:///home/ktietz/src/ci/decorator_1611930055503/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
dictdiffer @ file:///home/conda/feedstock_root/build_artifacts/dictdiffer_1618050327922/work
diff-match-patch @ file:///tmp/build/80754af9/diff-match-patch_1594828741838/work
dill @ file:///tmp/build/80754af9/dill_1605066453875/work
distributed @ file:///C:/ci/distributed_1621290374478/work
docutils @ file:///C:/ci/docutils_1620828260973/work
echo @ file:///home/conda/feedstock_root/build_artifacts/echo_1600378613587/work
entrypoints==0.3
ephem @ file:///C:/ci/ephem_1600337431654/work
et-xmlfile==1.1.0
fast-histogram @ file:///D:/bld/fast-histogram_1602504803709/work
fastcache==1.1.0
fbprophet @ file:///D:/bld/fbprophet_1599365958928/work
filelock @ file:///home/linux1/recipes/ci/filelock_1610993975404/work
flake8 @ file:///tmp/build/80754af9/flake8_1615834841867/work
Flask @ file:///home/ktietz/src/ci/flask_1611932660458/work
flatbuffers==1.12
freetype-py @ file:///home/conda/feedstock_root/build_artifacts/freetype-py_1594318845769/work
fsspec @ file:///tmp/build/80754af9/fsspec_1617959894824/work
future==0.18.2
gast==0.4.0
gevent @ file:///C:/ci/gevent_1616773090559/work
glob2 @ file:///home/linux1/recipes/ci/glob2_1610991677669/work
glue-core==1.0.1
glue-vispy-viewers==1.0.2
glueviz==1.0.0
gmpy2==2.0.8
google-auth @ file:///tmp/build/80754af9/google-auth_1619477128713/work
google-auth-oauthlib @ file:///tmp/build/80754af9/google-auth-oauthlib_1617120569401/work
google-pasta==0.2.0
greenlet @ file:///C:/ci/greenlet_1620913825737/work
grpcio==1.34.1
h11 @ file:///home/conda/feedstock_root/build_artifacts/h11_1609518832927/work
h2 @ file:///D:/bld/h2_1610644001948/work
h5py==3.1.0
HeapDict==1.0.1
hijri-converter @ file:///home/conda/feedstock_root/build_artifacts/hijri-converter_1612531902526/work
holidays @ file:///home/conda/feedstock_root/build_artifacts/holidays_1617373843485/work
hpack==4.0.0
html5lib @ file:///tmp/build/80754af9/html5lib_1593446221756/work
httpcore @ file:///home/conda/feedstock_root/build_artifacts/httpcore_1622121059249/work
httpx @ file:///D:/bld/httpx_1621322412083/work
hyperframe @ file:///home/conda/feedstock_root/build_artifacts/hyperframe_1619110129307/work
idna @ file:///home/linux1/recipes/ci/idna_1610986105248/work
imagecodecs @ file:///C:/ci/imagecodecs_1621408025737/work
imageio @ file:///tmp/build/80754af9/imageio_1617700267927/work
imagesize @ file:///home/ktietz/src/ci/imagesize_1611921604382/work
importlib-metadata @ file:///C:/ci/importlib-metadata_1617877484576/work
iniconfig @ file:///home/linux1/recipes/ci/iniconfig_1610983019677/work
intervaltree @ file:///tmp/build/80754af9/intervaltree_1598376443606/work
ipykernel @ file:///C:/ci/ipykernel_1596190155316/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///C:/ci/ipython_1617121002983/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1610481889018/work
isort @ file:///tmp/build/80754af9/isort_1616355431277/work
itsdangerous @ file:///tmp/build/80754af9/itsdangerous_1621432558163/work
jdcal==1.4.1
jedi @ file:///C:/ci/jedi_1592833825077/work
Jinja2 @ file:///tmp/build/80754af9/jinja2_1621238361758/work
joblib @ file:///tmp/build/80754af9/joblib_1613502643832/work
json5==0.9.5
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
jupyter==1.0.0
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1616770841739/work
jupyter-console @ file:///tmp/build/80754af9/jupyter_console_1616615302928/work
jupyter-core @ file:///C:/ci/jupyter_core_1612213356021/work
jupyter-packaging @ file:///tmp/build/80754af9/jupyter-packaging_1613502826984/work
jupyter-server @ file:///C:/ci/jupyter_server_1616084298403/work
jupyterlab @ file:///tmp/build/80754af9/jupyterlab_1619133235951/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
jupyterlab-server @ file:///tmp/build/80754af9/jupyterlab_server_1617134334258/work
jupyterlab-widgets @ file:///tmp/build/80754af9/jupyterlab_widgets_1609884341231/work
Keras @ file:///tmp/build/80754af9/keras_split_1593112142734/work
Keras-Applications @ file:///tmp/build/80754af9/keras-applications_1594366238411/work
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing @ file:///tmp/build/80754af9/keras-preprocessing_1612283640596/work
keyring @ file:///C:/ci/keyring_1621524753360/work
keyrings.alt @ file:///home/conda/feedstock_root/build_artifacts/keyrings.alt_1608136994844/work
kiwisolver @ file:///C:/ci/kiwisolver_1612282606037/work
korean-lunar-calendar @ file:///home/conda/feedstock_root/build_artifacts/korean_lunar_calendar_1589354365811/work
lazy-object-proxy @ file:///C:/ci/lazy-object-proxy_1616529307648/work
libarchive-c @ file:///tmp/build/80754af9/python-libarchive-c_1617780486945/work
llvmlite==0.36.0
locket==0.2.1
lockfile==0.12.2
LunarCalendar==0.0.9
lxml @ file:///C:/ci/lxml_1616443455957/work
Mako @ file:///tmp/build/80754af9/mako_1610650590832/work
Markdown @ file:///C:/ci/markdown_1614364121613/work
MarkupSafe @ file:///C:/ci/markupsafe_1621528314575/work
matplotlib @ file:///C:/ci/matplotlib-suite_1613408055530/work
mccabe==0.6.1
menuinst==1.4.16
mistune==0.8.4
mkl-fft==1.3.0
mkl-random @ file:///C:/ci/mkl_random_1618854156666/work
mkl-service==2.3.0
mock @ file:///tmp/build/80754af9/mock_1607622725907/work
more-itertools @ file:///tmp/build/80754af9/more-itertools_1613676688952/work
mpl-scatter-density @ file:///home/conda/feedstock_root/build_artifacts/mpl-scatter-density_1596626732308/work
mpmath==1.2.1
msgpack @ file:///C:/ci/msgpack-python_1612287368835/work
multidict @ file:///C:/ci/multidict_1607362065515/work
multipledispatch==0.6.0
navigator-updater==0.2.1
nbclassic @ file:///tmp/build/80754af9/nbclassic_1616085367084/work
nbclient @ file:///tmp/build/80754af9/nbclient_1614364831625/work
nbconvert @ file:///C:/ci/nbconvert_1601914925608/work
nbformat @ file:///tmp/build/80754af9/nbformat_1617383369282/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1613680548246/work
netCDF4 @ file:///C:/ci/netcdf4_1613684374643/work
networkx @ file:///tmp/build/80754af9/networkx_1617653298338/work
nltk @ file:///tmp/build/80754af9/nltk_1621347441292/work
nose @ file:///tmp/build/80754af9/nose_1606773131901/work
notebook @ file:///C:/ci/notebook_1621528634641/work
numba @ file:///C:/ci/numba_1616774458845/work
numexpr @ file:///C:/ci/numexpr_1618856738664/work
numpy==1.19.5
numpydoc @ file:///tmp/build/80754af9/numpydoc_1605117425582/work
oauthlib==3.1.0
olefile==0.46
openpyxl @ file:///tmp/build/80754af9/openpyxl_1615411699337/work
openTSNE @ file:///D:/bld/opentsne_1619416621658/work
opt-einsum @ file:///tmp/build/80754af9/opt_einsum_1621500238896/work
orange-canvas-core @ file:///home/conda/feedstock_root/build_artifacts/orange-canvas-core_1619791625969/work
orange-widget-base @ file:///home/conda/feedstock_root/build_artifacts/orange-widget-base_1622122538734/work
Orange3 @ file:///C:/ci/orange3_1594070678918/work
packaging @ file:///tmp/build/80754af9/packaging_1611952188834/work
pandas @ file:///C:/ci/pandas_1618365634936/work
pandocfilters @ file:///C:/ci/pandocfilters_1605102497129/work
paramiko @ file:///tmp/build/80754af9/paramiko_1598886428689/work
parso==0.7.0
partd @ file:///tmp/build/80754af9/partd_1618000087440/work
path @ file:///C:/ci/path_1614022440181/work
pathlib2 @ file:///C:/ci/pathlib2_1607025069150/work
pathtools==0.1.2
patsy==0.5.1
pep8==1.7.1
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow @ file:///C:/ci/pillow_1617386341487/work
pkginfo==1.7.0
pluggy @ file:///C:/ci/pluggy_1615976358795/work
ply==3.11
prometheus-client @ file:///tmp/build/80754af9/prometheus_client_1618088486455/work
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1616415428029/work
protobuf==3.14.0
psutil @ file:///C:/ci/psutil_1612298324802/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
py @ file:///tmp/build/80754af9/py_1607971587848/work
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle @ file:///home/ktietz/src/ci_mi/pycodestyle_1612807597675/work
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pycurl==7.43.0.6
pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1621600989141/work
pyerfa @ file:///C:/ci/pyerfa_1621561004681/work
pyflakes @ file:///home/ktietz/src/ci_ipy2/pyflakes_1612551159640/work
Pygments @ file:///tmp/build/80754af9/pygments_1621606182707/work
pygpu==0.7.6
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1617199158555/work
pylint @ file:///C:/ci/pylint_1617136058775/work
PyMeeus @ file:///home/conda/feedstock_root/build_artifacts/pymeeus_1615809745702/work
PyNaCl @ file:///C:/ci/pynacl_1595000047588/work
pyodbc===4.0.0-unsupported
PyOpenGL==3.1.1a1
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing @ file:///home/linux1/recipes/ci/pyparsing_1610983426697/work
pyqtgraph @ file:///tmp/build/80754af9/pyqtgraph_1594064840332/work
pyreadline==2.1
pyrsistent @ file:///C:/ci/pyrsistent_1600141795814/work
PySocks @ file:///C:/ci/pysocks_1605287845585/work
pystan==2.19.1.1
pytest==6.2.3
python-dateutil @ file:///home/ktietz/src/ci/python-dateutil_1611928101742/work
python-jsonrpc-server @ file:///tmp/build/80754af9/python-jsonrpc-server_1600278539111/work
python-language-server @ file:///tmp/build/80754af9/python-language-server_1600454544709/work
python-louvain @ file:///home/conda/feedstock_root/build_artifacts/python-louvain_1609125227889/work
pytz @ file:///tmp/build/80754af9/pytz_1612215392582/work
PyWavelets @ file:///C:/ci/pywavelets_1601658407916/work
pywin32==227
pywin32-ctypes==0.2.0
pywinpty==0.5.7
PyYAML==5.4.1
pyzmq==20.0.0
qasync @ file:///home/conda/feedstock_root/build_artifacts/qasync_1621235475021/work
QDarkStyle @ file:///tmp/build/80754af9/qdarkstyle_1617386714626/work
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1615991616277/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1616775094278/work
QtPy==1.9.0
regex @ file:///C:/ci/regex_1617569893741/work
requests @ file:///tmp/build/80754af9/requests_1608241421344/work
requests-oauthlib==1.3.0
rfc3986 @ file:///home/conda/feedstock_root/build_artifacts/rfc3986_1620442452971/work
rope @ file:///tmp/build/80754af9/rope_1602264064449/work
rsa @ file:///tmp/build/80754af9/rsa_1614366226499/work
Rtree @ file:///C:/ci/rtree_1618421009405/work
ruamel-yaml-conda @ file:///C:/ci/ruamel_yaml_1616016967756/work
scikit-image==0.18.1
scikit-learn @ file:///C:/ci/scikit-learn_1621370563523/work
scipy==1.4.1
seaborn @ file:///tmp/build/80754af9/seaborn_1608578541026/work
Send2Trash @ file:///tmp/build/80754af9/send2trash_1607525499227/work
serverfiles==0.3.0
setuptools-git==1.2
simplegeneric==0.8.1
singledispatch @ file:///tmp/build/80754af9/singledispatch_1614366001199/work
sip==4.19.13
six @ file:///C:/ci/six_1605187374963/work
sniffio @ file:///C:/ci/sniffio_1614030707456/work
snowballstemmer @ file:///tmp/build/80754af9/snowballstemmer_1611258885636/work
sortedcollections @ file:///tmp/build/80754af9/sortedcollections_1611172717284/work
sortedcontainers @ file:///tmp/build/80754af9/sortedcontainers_1606865132123/work
soupsieve @ file:///tmp/build/80754af9/soupsieve_1616183228191/work
Sphinx @ file:///tmp/build/80754af9/sphinx_1620777493457/work
sphinxcontrib-applehelp @ file:///home/ktietz/src/ci/sphinxcontrib-applehelp_1611920841464/work
sphinxcontrib-devhelp @ file:///home/ktietz/src/ci/sphinxcontrib-devhelp_1611920923094/work
sphinxcontrib-htmlhelp @ file:///home/ktietz/src/ci/sphinxcontrib-htmlhelp_1611920974801/work
sphinxcontrib-jsmath @ file:///home/ktietz/src/ci/sphinxcontrib-jsmath_1611920942228/work
sphinxcontrib-qthelp @ file:///home/ktietz/src/ci/sphinxcontrib-qthelp_1611921055322/work
sphinxcontrib-serializinghtml @ file:///home/ktietz/src/ci/sphinxcontrib-serializinghtml_1611920755253/work
sphinxcontrib-websupport @ file:///tmp/build/80754af9/sphinxcontrib-websupport_1597081412696/work
spyder @ file:///C:/ci/spyder_1599054115447/work
spyder-kernels @ file:///C:/ci/spyder-kernels_1599051709837/work
SQLAlchemy @ file:///C:/ci/sqlalchemy_1620712610212/work
statsmodels==0.12.2
sympy @ file:///C:/ci/sympy_1618255511605/work
tables==3.6.1
tblib @ file:///tmp/build/80754af9/tblib_1597928476713/work
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.6.0
tensorflow==2.3.0
tensorflow-estimator==2.5.0
tensorflow-gpu==2.5.0
termcolor==1.1.0
terminado==0.9.4
testpath @ file:///home/ktietz/src/ci/testpath_1611930608132/work
Theano==1.0.4
threadpoolctl @ file:///tmp/tmp9twdgx9k/threadpoolctl-2.1.0-py3-none-any.whl
tifffile @ file:///tmp/build/80754af9/tifffile_1619636090847/work
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
toolz @ file:///home/linux1/recipes/ci/toolz_1610987900194/work
tornado @ file:///C:/ci/tornado_1606942392901/work
tqdm @ file:///tmp/build/80754af9/tqdm_1615925068909/work
traitlets @ file:///home/ktietz/src/ci/traitlets_1611929699868/work
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1611751222202/work
ujson @ file:///C:/ci/ujson_1611241570789/work
unicodecsv==0.14.1
urllib3 @ file:///tmp/build/80754af9/urllib3_1615837158687/work
vispy @ file:///D:/bld/vispy_1619790282256/work
watchdog @ file:///C:/ci/watchdog_1620778415875/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
Werkzeug @ file:///home/ktietz/src/ci/werkzeug_1611932622770/work
widgetsnbextension==3.5.1
win-inet-pton @ file:///C:/ci/win_inet_pton_1605306167264/work
win-unicode-console==0.5
wincertstore==0.2
wrapt==1.12.1
xarray @ file:///tmp/build/80754af9/xarray_1620826949436/work
xlrd @ file:///tmp/build/80754af9/xlrd_1608072521494/work
XlsxWriter @ file:///tmp/build/80754af9/xlsxwriter_1617224712951/work
xlwings==0.23.0
xlwt==1.3.0
xmltodict==0.12.0
yapf @ file:///tmp/build/80754af9/yapf_1615749224965/work
yarl @ file:///C:/ci/yarl_1606940076464/work
zict==2.0.0
zipp @ file:///tmp/build/80754af9/zipp_1615904174917/work
zope.event==4.5.0
zope.interface @ file:///C:/ci/zope.interface_1616357322857/work

WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)

In [78]:
!pip3 list

Package                            Version

WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)

---------------------------------- -------------------
absl-py                            0.12.0
aiohttp                            3.7.4
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 2.0.3
anaconda-project                   0.10.0
anyio                              2.2.0
AnyQt                              0.0.13
argh                               0.26.2
argon2-cffi                        20.1.0
arviz                              0.11.2
asn1crypto                         1.4.0
astor                              0.8.1
astroid                            2.5
astropy                            4.2.1
astunparse                         1.6.3
async-generator                    1.10
async-timeout                      3.0.1
atomicwrites                       1.4.0
attrs                              21.2.0
autopep8                           1.5.6
Babel                              2.9.1
backcall                           0.2.0
backports.functools-lru-cache      1.6.4
backports.shutil-get-terminal-size 1.0.0
backports.tempfile                 1.0
backports.weakref                  1.0.post1
baycomp                            1.0.2
bcrypt                             3.2.0
beautifulsoup4                     4.9.3
bitarray                           2.1.0
bkcharts                           0.2
bleach                             3.3.0
blinker                            1.4
bokeh                              2.3.2
boto                               2.49.0
Bottleneck                         1.3.2
brotlipy                           0.7.0
CacheControl                       0.12.6
cachetools                         4.2.2
certifi                            2020.12.5
cffi                               1.14.5
cftime                             1.5.0
chardet                            3.0.4
click                              8.0.1
cloudpickle                        1.6.0
clyent                             1.2.2
cmdstanpy                          0.9.75
colorama                           0.4.4
commonmark                         0.9.1
comtypes                           1.1.10
conda                              4.10.1
conda-build                        3.21.4
conda-content-trust                0+unknown
conda-pack                         0.6.0
conda-package-handling             1.7.3
conda-repo-cli                     1.0.4
conda-token                        0.3.0
conda-verify                       3.4.2
contextlib2                        0.6.0.post1
convertdate                        2.3.2
coverage                           5.5
cryptography                       3.4.7
cycler                             0.10.0
Cython                             0.29.23
cytoolz                            0.11.0
dask                               2021.4.0
decorator                          4.4.2
defusedxml                         0.7.1
dictdiffer                         0.8.1
diff-match-patch                   20200713
dill                               0.3.3
distributed                        2021.5.0
docutils                           0.17.1
echo                               0.5
entrypoints                        0.3
ephem                              3.7.7.1
et-xmlfile                         1.1.0
fast-histogram                     0.0.0
fastcache                          1.1.0
fbprophet                          0.7.1
filelock                           3.0.12
flake8                             3.9.0
Flask                              1.1.2
flatbuffers                        1.12
freetype-py                        2.2.0
fsspec                             0.9.0
future                             0.18.2
gast                               0.4.0
gevent                             21.1.2
glob2                              0.7
glue-core                          1.0.1
glue-vispy-viewers                 1.0.2
glueviz                            1.0.0
gmpy2                              2.0.8
google-auth                        1.30.0
google-auth-oauthlib               0.4.4
google-pasta                       0.2.0
greenlet                           1.1.0
grpcio                             1.34.1
h11                                0.12.0
h2                                 4.0.0
h5py                               3.1.0
HeapDict                           1.0.1
hijri-converter                    2.1.1
holidays                           0.11.1
hpack                              4.0.0
html5lib                           1.1
httpcore                           0.13.3
httpx                              0.18.1
hyperframe                         6.0.1
idna                               2.10
imagecodecs                        2021.4.28
imageio                            2.9.0
imagesize                          1.2.0
importlib-metadata                 3.10.0
iniconfig                          1.1.1
intervaltree                       3.1.0
ipykernel                          5.3.4
ipython                            7.22.0
ipython-genutils                   0.2.0
ipywidgets                         7.6.3
isort                              5.8.0
itsdangerous                       2.0.1
jdcal                              1.4.1
jedi                               0.17.1
Jinja2                             3.0.0
joblib                             1.0.1
json5                              0.9.5
jsonschema                         3.2.0
jupyter                            1.0.0
jupyter-client                     6.1.12
jupyter-console                    6.4.0
jupyter-core                       4.7.1
jupyter-packaging                  0.7.12
jupyter-server                     1.4.1
jupyterlab                         3.0.14
jupyterlab-pygments                0.1.2
jupyterlab-server                  2.4.0
jupyterlab-widgets                 1.0.0
Keras                              2.4.3
Keras-Applications                 1.0.8
keras-nightly                      2.5.0.dev2021032900
Keras-Preprocessing                1.1.2
keyring                            23.0.1
keyrings.alt                       4.0.2
kiwisolver                         1.3.1
korean-lunar-calendar              0.2.1
lazy-object-proxy                  1.6.0
libarchive-c                       2.9
llvmlite                           0.36.0
locket                             0.2.1
lockfile                           0.12.2
LunarCalendar                      0.0.9
lxml                               4.6.3
Mako                               1.1.4
Markdown                           3.3.4
MarkupSafe                         2.0.1
matplotlib                         3.3.4
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.3.0
mkl-random                         1.2.1
mkl-service                        2.3.0
mock                               4.0.3
more-itertools                     8.7.0
mpl-scatter-density                0.7
mpmath                             1.2.1
msgpack                            1.0.2
multidict                          5.1.0
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbclassic                          0.2.6
nbclient                           0.5.3
nbconvert                          6.0.7
nbformat                           5.1.3
nest-asyncio                       1.5.1
netCDF4                            1.5.6
networkx                           2.5.1
nltk                               3.6.2
nose                               1.3.7
notebook                           6.4.0
numba                              0.53.1
numexpr                            2.7.3
numpy                              1.19.5
numpydoc                           1.1.0
oauthlib                           3.1.0
olefile                            0.46
openpyxl                           3.0.7
openTSNE                           0.6.0
opt-einsum                         3.3.0
orange-canvas-core                 0.1.20
orange-widget-base                 4.13.1
Orange3                            3.26.0
packaging                          20.9
pandas                             1.2.4
pandocfilters                      1.4.3
paramiko                           2.7.2
parso                              0.7.0
partd                              1.2.0
path                               15.1.2
pathlib2                           2.3.5
pathtools                          0.1.2
patsy                              0.5.1
pep8                               1.7.1
pexpect                            4.8.0
pickleshare                        0.7.5
Pillow                             8.2.0
pip                                21.1.1
pkginfo                            1.7.0
pluggy                             0.13.1
ply                                3.11
prometheus-client                  0.10.1
prompt-toolkit                     3.0.17
protobuf                           3.14.0
psutil                             5.8.0
ptyprocess                         0.7.0
py                                 1.10.0
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.6.0
pycosat                            0.6.3
pycparser                          2.20
pycurl                             7.43.0.6
pydocstyle                         6.1.1
pyerfa                             2.0.0
pyflakes                           2.2.0
Pygments                           2.9.0
pygpu                              0.7.6
PyJWT                              2.0.1
pylint                             2.7.4
PyMeeus                            0.5.10
PyNaCl                             1.4.0
pyodbc                             4.0.0-unsupported
PyOpenGL                           3.1.1a1
pyOpenSSL                          20.0.1

pyparsing                          2.4.7
pyqtgraph                          0.11.0
pyreadline                         2.1
pyrsistent                         0.17.3
PySocks                            1.7.1
pystan                             2.19.1.1
pytest                             6.2.3
python-dateutil                    2.8.1
python-jsonrpc-server              0.4.0
python-language-server             0.35.1
python-louvain                     0.15
pytz                               2021.1
PyWavelets                         1.1.1
pywin32                            227
pywin32-ctypes                     0.2.0
pywinpty                           0.5.7
PyYAML                             5.4.1
pyzmq                              20.0.0
qasync                             0.16.0
QDarkStyle                         3.0.2
QtAwesome                          1.0.2
qtconsole                          5.0.3
QtPy                               1.9.0
regex                              2021.4.4
requests                           2.25.1
requests-oauthlib                  1.3.0
rfc3986                            1.5.0
rope                               0.18.0
rsa                                4.7.2
Rtree                              0.9.7
ruamel-yaml-conda                  0.15.100
scikit-image                       0.18.1
scikit-learn                       0.24.2
scipy                              1.4.1
seaborn                            0.11.1
Send2Trash                         1.5.0
serverfiles                        0.3.0
setuptools                         52.0.0.post20210125
setuptools-git                     1.2
simplegeneric                      0.8.1
singledispatch                     0.0.0
sip                                4.19.13
six                                1.15.0
sniffio                            1.2.0
snowballstemmer                    2.1.0
sortedcollections                  2.1.0
sortedcontainers                   2.3.0
soupsieve                          2.2.1
Sphinx                             4.0.1
sphinxcontrib-applehelp            1.0.2
sphinxcontrib-devhelp              1.0.2
sphinxcontrib-htmlhelp             1.0.3
sphinxcontrib-jsmath               1.0.1
sphinxcontrib-qthelp               1.0.3
sphinxcontrib-serializinghtml      1.1.4
sphinxcontrib-websupport           1.2.4
spyder                             4.1.5
spyder-kernels                     1.9.4
SQLAlchemy                         1.4.15
statsmodels                        0.12.2
sympy                              1.8
tables                             3.6.1
tblib                              1.7.0
tensorboard                        2.5.0
tensorboard-data-server            0.6.1
tensorboard-plugin-wit             1.6.0
tensorflow                         2.3.0
tensorflow-estimator               2.5.0
tensorflow-gpu                     2.5.0
termcolor                          1.1.0
terminado                          0.9.4
testpath                           0.4.4
Theano                             1.0.4
threadpoolctl                      2.1.0
tifffile                           2021.4.8
toml                               0.10.2
toolz                              0.11.1
tornado                            6.1
tqdm                               4.59.0
traitlets                          5.0.5
typing-extensions                  3.7.4.3
ujson                              4.0.2
unicodecsv                         0.14.1
urllib3                            1.26.4
vispy                              0.6.6
watchdog                           2.1.1
wcwidth                            0.2.5
webencodings                       0.5.1
Werkzeug                           1.0.1
wheel                              0.36.2
widgetsnbextension                 3.5.1
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.12.1
xarray                             0.18.0
xlrd                               2.0.1
XlsxWriter                         1.3.8
xlwings                            0.23.0
xlwt                               1.3.0
xmltodict                          0.12.0
yapf                               0.31.0
yarl                               1.6.3
zict                               2.0.0
zipp                               3.4.1
zope.event                         4.5.0
zope.interface                     5.3.0

In [85]:
!pip3 freeze > requirements_20210607.txt

WARNING: Ignoring invalid distribution -umpy (c:\programdata\anaconda3\lib\site-packages)